export * from "./Landing";
export * from "./Location";
export * from "./Home";
export * from "./Store";
export * from "./Orders";
export * from "./Cart";
export * from "./Profile";
export * from "./Login";
export * from "./Otp";
